spring.application.name=proyect
spring.datasource.url=jdbc:postgresql://localhost:5432/proyect
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.web.resources.static-locations=file:front/

# JWT Configuration
jwt.secret=d8aF92ksLmPq78XzRtUvW1yB6nHjK3sQ
jwt.expiration=3600000

# spring.jpa.hibernate.ddl-auto=update   esto se quita para crear las tablas a mano
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.proyect=DEBUG

# Game configuration
game.actions-per-turn=10
game.vision-range-naval=4
game.vision-range-aereo=6

# Missile configuration
game.missile.max-distance=15
game.missile.damage-percent-on-naval=0.5

# Unit balance configurable by faction
# Aereo
game.units.aereo.max-hp=100
game.units.aereo.movement-range=2
game.units.aereo.max-fuel=10
game.units.aereo.vision-range=6
game.units.aereo.ammo=1
game.units.aereo.carrier-hp=6
game.units.aereo.carrier-movement-range=3

# Naval
game.units.naval.max-hp=100
game.units.naval.movement-range=2
game.units.naval.max-fuel=10
game.units.naval.vision-range=4
game.units.naval.weapon-ammo=10
game.units.naval.missiles=2
game.units.naval.carrier-hp=3
game.units.naval.carrier-movement-range=1
